### ISSUE TITLE
error occurred

### ISSUE THREAD

**Issue by luckychris** [erikmartens/NearbyWeather#161]
PreferencesManagerStoredContents.json missing. what have i to do to make it run?

**Comment by erikmartens** [comment]
@luckychris Hi Christoph, this is a debug console message that is expected to appear the first time you run the app, since no preferences have been save yet. This should not prevent the app from running, as it will only appear once the app starts running.

Let me know if you have any other questions.

**Comment by luckychris** [comment]
you are right. ok, did sound like an error ;)
